M48
; DRILL file {KiCad 9.0.7} date 2026-07-27T20:51:32-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-27T20:51:32-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X77.82Y-65.11
X77.82Y-70.89
T2
X22.5Y-28.0
X22.5Y-77.5
X82.0Y-28.0
X82.0Y-77.5
M30
